name: mcr_gsab
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py36_1000
  - backcall=0.1.0=py_0
  - basemap=1.2.0=py36h50ae964_0
  - bleach=2.1.4=py_1
  - bzip2=1.0.6=1
  - ca-certificates=2018.8.24=ha4d7672_0
  - certifi=2018.8.24=py36_1001
  - clangdev=6.0.1=default_1
  - cycler=0.10.0=py_1
  - decorator=4.3.0=py_0
  - entrypoints=0.2.3=py36_1002
  - freetype=2.9.1=h6debe1e_4
  - future=0.16.0=py36_1002
  - geos=3.6.2=hfc679d8_3
  - html5lib=1.0.1=py_0
  - icu=58.2=hfc679d8_0
  - ipykernel=5.0.0=pyh24bf2e0_1
  - ipython=7.0.1=py36h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py_0
  - jedi=0.13.1=py36_1000
  - jinja2=2.10=py_1
  - jpeg=9c=h470a237_1
  - jsonschema=2.6.0=py36_1002
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.3=py_1
  - jupyter_console=5.1.0=py36_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.0.1=py36h2d50403_2
  - libcxx=6.0.1=0
  - libffi=3.2.1=hfc679d8_5
  - libiconv=1.15=h470a237_3
  - libpng=1.6.35=ha92aebf_2
  - libsodium=1.0.16=h470a237_1
  - libxml2=2.9.8=h422b904_5
  - llvm-meta=6.0.1=0
  - llvmdev=6.0.1=hf8ce74a_2
  - markupsafe=1.0=py36h470a237_1
  - matplotlib=3.0.0=py36h45c993b_1
  - mistune=0.8.3=py36h470a237_2
  - mkl_fft=1.0.6=py36_0
  - mkl_random=1.0.1=py36_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hfc679d8_1
  - notebook=5.7.0=py36_0
  - openblas=0.2.20=8
  - openssl=1.0.2p=h470a237_0
  - pandas=0.23.4=py36hf8a1672_0
  - pandoc=2.3.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.3.1=py_0
  - pexpect=4.6.0=py36_1000
  - pickleshare=0.7.5=py36_1000
  - pip=18.0=py36_1001
  - proj4=5.2.0=h470a237_0
  - prometheus_client=0.3.1=py_1
  - prompt_toolkit=2.0.5=py_0
  - ptyprocess=0.6.0=py36_1000
  - pygments=2.2.0=py_1
  - pyparsing=2.2.2=py_0
  - pyproj=1.9.5.1=py36_0
  - pyqt=5.6.0=py36h8210e8a_7
  - pyshp=1.2.12=py_0
  - python=3.6.6=h5001a0f_0
  - python-dateutil=2.7.3=py_0
  - pytz=2018.5=py_0
  - pyzmq=17.1.2=py36hae99301_0
  - qt=5.6.2=hd4c90f3_9
  - qtconsole=4.4.1=py36_1
  - readline=7.0=haf1bffa_1
  - send2trash=1.5.0=py_0
  - setuptools=40.4.3=py36_0
  - simplegeneric=0.8.1=py_1
  - sip=4.18.1=py36hfc679d8_0
  - six=1.11.0=py36_1001
  - sqlite=3.25.2=hb1c47c0_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36_1
  - tk=8.6.8=ha92aebf_0
  - tornado=5.1.1=py36h470a237_0
  - traitlets=4.3.2=py36_1000
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.32.0=py36_1000
  - widgetsnbextension=3.4.2=py36_0
  - xz=5.2.4=h470a237_1
  - zeromq=4.2.5=hfc679d8_5
  - zlib=1.2.11=h470a237_3
  - blas=1.0=mkl
  - intel-openmp=2019.0=118
  - libgfortran=3.0.1=h93005f0_2
  - libopenblas=0.3.3=hdc02c5d_3
  - mkl=2019.0=118
  - numpy=1.15.2=py36h6a91979_1
  - numpy-base=1.15.2=py36h8a80b8c_1
  - scipy=1.1.0=py36h28f7352_1
  - pip:
    - appdirs==1.4.3
    - pmagpy==3.11.1
prefix: /anaconda3/envs/mcr_gsab

