name: kewee_track
channels:
- scitools
- defaults
dependencies:
- backports=1.0=py27_0
- backports_abc=0.5=py27_0
- bleach=1.5.0=py27_0
- cairo=1.14.8=0
- configparser=3.5.0=py27_0
- cycler=0.10.0=py27_0
- decorator=4.0.11=py27_0
- entrypoints=0.2.2=py27_1
- enum34=1.1.6=py27_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- funcsigs=1.0.2=py27_0
- functools32=3.2.3.2=py27_0
- get_terminal_size=1.0.0=py27_0
- glib=2.50.2=1
- harfbuzz=0.9.39=2
- html5lib=0.999=py27_0
- ipykernel=4.6.1=py27_0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- jbig=2.1=0
- jinja2=2.9.6=py27_0
- jpeg=9b=0
- jsonschema=2.6.0=py27_0
- jupyter_client=5.0.1=py27_0
- jupyter_core=4.3.0=py27_0
- libffi=3.2.1=1
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libxml2=2.9.4=0
- libxslt=1.1.29=0
- lxml=3.8.0=py27_0
- markupsafe=0.23=py27_2
- matplotlib=1.5.1=np110py27_0
- mistune=0.7.4=py27_0
- mkl=11.3.3=0
- mock=2.0.0=py27_0
- nbconvert=5.2.1=py27_0
- nbformat=4.3.0=py27_0
- nose=1.3.7=py27_1
- notebook=5.0.0=py27_0
- numpy=1.10.2=py27_0
- openblas=0.2.14=4
- openssl=1.0.2l=0
- pandas=0.18.1=np110py27_0
- pandocfilters=1.4.1=py27_0
- pango=1.40.3=1
- path.py=10.3.1=py27_0
- pathlib2=2.2.1=py27_0
- pbr=1.10.0=py27_0
- pcre=8.39=1
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pillow=4.1.1=py27_0
- pip=9.0.1=py27_1
- pixman=0.34.0=0
- prompt_toolkit=1.0.14=py27_0
- ptyprocess=0.5.1=py27_0
- pycairo=1.10.0=py27_0
- pygments=2.2.0=py27_0
- pymc=2.3.6=np110py27_1
- pyparsing=2.1.4=py27_0
- pyproj=1.9.5.1=py27_0
- pyqt=4.11.4=py27_4
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- pytz=2017.2=py27_0
- pyzmq=16.0.2=py27_0
- qt=4.8.7=4
- readline=6.2=2
- requests=2.14.2=py27_0
- scandir=1.5=py27_0
- scipy=0.17.0=np110py27_4
- seaborn=0.7.1=py27_0
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- terminado=0.6=py27_0
- testpath=0.3.1=py27_0
- tk=8.5.18=0
- tornado=4.5.1=py27_0
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- xz=5.2.2=1
- zeromq=4.1.5=0
- zlib=1.2.8=3
- cartopy=0.15.0=np110py27_0
- geos=3.4.2=4
- olefile=0.42.1=py27_1
- owslib=0.10.3=py27_0
- proj.4=4.9.1=1
- pyepsg=0.2.0=py27_0
- pyshp=1.2.3=py27_0
- shapely=1.5.13=np110py27_1
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.1
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.14
prefix: /home/ian/anaconda/envs/kewee_track

